[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#0EA5E9"
backgroundColor = "#030712"
secondaryBackgroundColor = "#0F172A"
textColor = "#F3F4F6"
font = "sans serif"
